### PR TITLE
implement a first vue.js app instead of a bunch of jquery

### PR DESCRIPTION
**Pull request by phoet**
tried some vue.js and i liked it! thx @dennisreimann 

vue

### CODE REVIEW

**Comment by dennisreimann** [comment]
Nice 👍  I like Vue a lot, especially for the components part.  Compared to similar libs it has a nice learning curve and you get something on the screen quickly.

**Comment by phoet** [comment]
yeah, i was really pleased! i only spent 3 hours last night and i never felt lost. the only thing that did not work as i wanted and where i spent most time on was to integration with bootstrap tooltip. i guess there are some pitfalls to be found further down the road...

**Comment by dennisreimann** [comment]
Maybe that's a bootstrap bindung issue. The components might get (re)rendered several times and you may need to unbind/rebind in [beforeDestroy/updated](https://vuejs.org/guide/instance.html#Lifecycle-Diagram).

**Comment by phoet** [comment]
Ah nice, helpful diagrams are helpful!

**Pull request merged**
